# docker-compose.yml
version: '3.4'

services:
  berry-dashboard-db:
    container_name: "berry-dashboard-db"
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=berry-dashboard-db"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
  berry-dashboard-db-admin:
    container_name: "berry-dashboard-db-admin"
    image: dpage/pgadmin4
    ports:
      - "5480:80"
    expose:
      - "80"
    volumes:
      - "./pgadmin:/var/lib/pgadmin"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=public.bluemiv@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=1234"